/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Business.Swing;

import Data.Model.Account;
import Data.Repository.Admin.ResourceRepository;
import Data.Repository.User.AccountRepository;
import Utils.ImageUtils;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author ADMIN
 */
public class Login extends javax.swing.JFrame {

    private ResourceRepository repository = new ResourceRepository();

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            logo_content.setIcon(new ImageIcon(
                    ImageUtils.convertByteToImage(repository.getImageByName("logo"))
                            .getScaledInstance(121, 120, Image.SCALE_SMOOTH)));
        } catch (Exception e) {
        }
        login_title.requestFocusInWindow();
        login_register.addHyperlinkListener((HyperlinkEvent e) -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.browse(e.getURL().toURI());
                } catch (Exception ex) {
                }
            }
        });

        login_forgotPass.addHyperlinkListener((HyperlinkEvent e) -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.browse(e.getURL().toURI());
                } catch (Exception ex) {
                }
            }
        });

        login_aboutus.addHyperlinkListener((HyperlinkEvent e) -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.browse(e.getURL().toURI());
                } catch (Exception ex) {
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_panel = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        logo_content = new javax.swing.JLabel();
        login_title = new javax.swing.JLabel();
        login_input_username = new javax.swing.JTextField();
        login_input_password = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        login_register = new javax.swing.JEditorPane();
        login_forgotPass = new javax.swing.JEditorPane();
        login_aboutus = new javax.swing.JEditorPane();
        web_banner = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        login_panel.setBackground(new java.awt.Color(229, 234, 240));
        login_panel.setPreferredSize(new java.awt.Dimension(307, 0));

        logo.setOpaque(false);

        logo_content.setToolTipText("");
        logo_content.setOpaque(true);

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_content, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        login_title.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        login_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title.setText("LOGIN");
        login_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        login_input_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_input_username.setForeground(new java.awt.Color(204, 204, 204));
        login_input_username.setText("Username/Email");
        login_input_username.setToolTipText("");
        login_input_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        login_input_username.setPreferredSize(new java.awt.Dimension(75, 40));
        login_input_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_input_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_input_usernameFocusLost(evt);
            }
        });
        login_input_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_input_usernameKeyPressed(evt);
            }
        });

        login_input_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_input_password.setForeground(new java.awt.Color(204, 204, 204));
        login_input_password.setText("Password");
        login_input_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        login_input_password.setEchoChar((char) 0);
        login_input_password.setPreferredSize(new java.awt.Dimension(207, 40));
        login_input_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_input_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_input_passwordFocusLost(evt);
            }
        });
        login_input_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_input_passwordKeyPressed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(51, 255, 204));
        login_button.setFont(new java.awt.Font("BIZ UDPGothic", 0, 18)); // NOI18N
        login_button.setText("Login");
        login_button.setBorder(null);
        login_button.setFocusPainted(false);
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        login_register.setEditable(false);
        login_register.setBackground(new java.awt.Color(229, 234, 240));
        login_register.setContentType("text/html"); // NOI18N
        login_register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_register.setText("<html>\r\n  <head>\r\n\r\t<style> \n\tbody {\nfont-family: 'tahoma';\nfont-size: 9px;\n}\n</style>\n  </head>\r\n  <body>\r\n<div style='text-align: center'>\n<a href='https://www.facebook.com' style='text-decoration: none; color: black; font-weight: bold;'>No account? Register here</a>\n</div>\n  \n  </body>\r\n</html>\r\n");
        login_register.setFocusable(false);
        login_register.setPreferredSize(new java.awt.Dimension(177, 20));

        login_forgotPass.setEditable(false);
        login_forgotPass.setBackground(new java.awt.Color(229, 234, 240));
        login_forgotPass.setContentType("text/html"); // NOI18N
        login_forgotPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login_forgotPass.setText("<html>\r\n  <head>\r\n\r\t<style> \n\tbody {\nfont-family: 'tahoma';\nfont-size: 9px;\n}\n</style>\n  </head>\r\n  <body>\r\n<div style='text-align: center'>\n  <a href='https://www.youtube.com' style='text-decoration: none; color: black; font-weight: bold;'>\n\tForgot password?\n  </a>\n</div>\n  </body>\r\n</html>\r\n");
        login_forgotPass.setFocusable(false);

        login_aboutus.setEditable(false);
        login_aboutus.setBackground(new java.awt.Color(229, 234, 240));
        login_aboutus.setBorder(null);
        login_aboutus.setContentType("text/html"); // NOI18N
        login_aboutus.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        login_aboutus.setText("<html>\n  <head>\n\t<style> \n\tbody {\nfont-family: 'tahoma';\nfont-size: 10px;\nfont-style: italic;\n}\n</style>\n  </head>\n  <body>\n<div style='text-align: center'>\n <a href='https://www.fb.com/dangtran1301' style='text-decoration: none; color: black; font-weight: italic;'>\n \tCopyright © 2024 Yama, Inc. FPTU Can Tho\n  </a>\n</div>\n  </body>\n</html>\n");
        login_aboutus.setFocusable(false);

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_input_password, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(login_aboutus)
            .addComponent(login_forgotPass)
            .addComponent(login_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(login_input_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(login_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_forgotPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(login_aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        web_banner.setBackground(new java.awt.Color(255, 102, 153));
        web_banner.setPreferredSize(new java.awt.Dimension(717, 0));

        javax.swing.GroupLayout web_bannerLayout = new javax.swing.GroupLayout(web_banner);
        web_banner.setLayout(web_bannerLayout);
        web_bannerLayout.setHorizontalGroup(
            web_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        web_bannerLayout.setVerticalGroup(
            web_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(web_banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addComponent(web_banner, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_input_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_input_usernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login_button.doClick();
        }
    }//GEN-LAST:event_login_input_usernameKeyPressed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username = login_input_username.getText().trim();
        String password = new String(login_input_password.getPassword());
        if (username.equals("Username/Email") || password.equals("Password")) {
            JOptionPane.showMessageDialog(this, "All field must be provided", "Empty input", JOptionPane.OK_OPTION);
            return;
        }
        Account account = new AccountRepository().login(username, password);
        if (account == null) {
            JOptionPane.showMessageDialog(this, "Your information provided is not correct", "User error", JOptionPane.OK_OPTION);
            login_input_username.setBorder(BorderFactory.createCompoundBorder(new LineBorder(Color.RED), new EmptyBorder(5, 10, 5, 10)));
            login_input_password.setBorder(BorderFactory.createCompoundBorder(new LineBorder(Color.RED), new EmptyBorder(5, 10, 5, 10)));
            return;
        }

        this.dispose();
        if (account.isRole()) {
            new Dashboard();
        } else {
            new Profile(account);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void login_input_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_input_usernameFocusGained
        if (login_input_username.getText().equals("Username/Email")) {
            login_input_username.setText("");
            login_input_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_login_input_usernameFocusGained

    private void login_input_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_input_usernameFocusLost
        if (login_input_username.getText().isEmpty()) {
            login_input_username.setText("Username/Email");
            login_input_username.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_login_input_usernameFocusLost

    private void login_input_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_input_passwordFocusGained
        char[] password = login_input_password.getPassword();
        if (password.length == 0 || new String(password).equals("Password")) {
            login_input_password.setEchoChar('*'); // Change echo char to '*' when focused
            login_input_password.setText("");
            login_input_password.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_login_input_passwordFocusGained

    private void login_input_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_input_passwordFocusLost
        char[] password = login_input_password.getPassword();
        if (password.length == 0) {
            login_input_password.setEchoChar((char) 0); // Set echo char to 0 to show actual text
            login_input_password.setText("Password");
            login_input_password.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_login_input_passwordFocusLost

    private void login_input_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_input_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login_button.doClick();
        }
    }//GEN-LAST:event_login_input_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane login_aboutus;
    private javax.swing.JButton login_button;
    private javax.swing.JEditorPane login_forgotPass;
    private javax.swing.JPasswordField login_input_password;
    private javax.swing.JTextField login_input_username;
    private javax.swing.JPanel login_panel;
    private javax.swing.JEditorPane login_register;
    private javax.swing.JLabel login_title;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logo_content;
    private javax.swing.JPanel web_banner;
    // End of variables declaration//GEN-END:variables
}
