/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Swing.Component;


import Business.Swing.Component.Subcomponent.CustomScrollBarUI;
import Data.Model.Feedback;
import Data.Repository.Admin.ResourceRepository;
import Utils.ImageUtils;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class FeedbackPanel extends javax.swing.JLayeredPane {

    private Feedback feedback;

    public Feedback getFeedback() {
        return feedback;
    }

    public FeedbackPanel(Feedback feedback) {
        initComponents();
        this.feedback = feedback;
        txt.setText(feedback.getFeedback());
        if (feedback.getAccount().getProfile().getImage() != null) {
            image.setIcon(new ImageIcon(
                    ImageUtils.convertByteToImage(feedback.getAccount().getProfile().getImage())
                            .getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        } else {
            image.setIcon(new ImageIcon(                    
                    ImageUtils.convertByteToImage(new ResourceRepository().getImageByName("logo"))
                            .getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        }
        date.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(feedback.getFeedbackDate()));
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        this.setSize(400, 50);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new Business.Swing.Component.Subcomponent.ChatText();
        image = new Business.Swing.Component.Subcomponent.ImageAvatar();

        setBackground(new java.awt.Color(255, 255, 255));

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("2024/04/05 00:00:00");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt.setEditable(false);
        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txt.setBgColor(new java.awt.Color(221, 246, 255));
        txt.setBorderColor(new java.awt.Color(6, 126, 183));
        txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt.setEnabled(false);
        txt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(txt);

        image.setPreferredSize(new java.awt.Dimension(30, 30));

        setLayer(date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private Business.Swing.Component.Subcomponent.ImageAvatar image;
    private javax.swing.JScrollPane jScrollPane1;
    private Business.Swing.Component.Subcomponent.ChatText txt;
    // End of variables declaration//GEN-END:variables
}
