/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.Swing.Component;

import Data.Model.Product;
import Utils.ImageUtils;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import Business.Swing.ProductDetail;
import Data.Model.Account;

/**
 *
 * @author ADMIN
 */
public class ProductCard extends javax.swing.JPanel {

    private Product product;
    private Account account;

    public ProductCard(Product product, Color color, Account account) {
        initComponents();
        this.product = product;
        this.account = account;
        setBackground(color);
        ProductCategory.setText(product.getCategory().getName());
        ProductPrice.setText("$" + product.getPrice());
        ProductImage.setIcon(new ImageIcon(ImageUtils.convertByteToImage(product.getImage()).getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        ProductName.setText(product.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductCategory = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JLabel();
        ProductImage = new Business.Swing.Component.Subcomponent.ImageAvatar();
        ProductName = new javax.swing.JLabel();
        ButtonView = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setPreferredSize(new java.awt.Dimension(150, 300));

        ProductCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProductCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductCategory.setText("Category");
        ProductCategory.setPreferredSize(new java.awt.Dimension(150, 50));

        ProductPrice.setBackground(new java.awt.Color(153, 255, 153));
        ProductPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProductPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductPrice.setText("$100");
        ProductPrice.setOpaque(true);
        ProductPrice.setPreferredSize(new java.awt.Dimension(150, 30));

        ProductName.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ProductName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductName.setText("Product Name");
        ProductName.setPreferredSize(new java.awt.Dimension(150, 30));

        ButtonView.setBackground(new java.awt.Color(0, 153, 255));
        ButtonView.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ButtonView.setForeground(new java.awt.Color(255, 255, 255));
        ButtonView.setText("VIEW DETAIL");
        ButtonView.setBorder(null);
        ButtonView.setBorderPainted(false);
        ButtonView.setFocusPainted(false);
        ButtonView.setPreferredSize(new java.awt.Dimension(140, 30));
        ButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewActionPerformed
        new ProductDetail(product, account);
    }//GEN-LAST:event_ButtonViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonView;
    private javax.swing.JLabel ProductCategory;
    private Business.Swing.Component.Subcomponent.ImageAvatar ProductImage;
    private javax.swing.JLabel ProductName;
    private javax.swing.JLabel ProductPrice;
    // End of variables declaration//GEN-END:variables
}
